config/routes.rb
Rails.application.routes.draw do
  root 'contents#index'
  devise_for :users
  resources :contents do
    resources :likes, only: [:create, :destroy]

    collection do
      get 'search_title'
      get 'search_content'
    end

  end

  resources :users, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
  acts_as_taggable
  acts_as_taggable_on :labels

  belongs_to :user
  has_many :likes, dependent: :destroy

  def self.search_title(search)
    return Content.all unless search
    Content.where('title LIKE(?)', "%#{search}%")
  end


  def self.search_content(search)
    return Content.all unless search
    Content.where('content LIKE(?)', "%#{search}%")
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :content
  belongs_to :user

  validates_uniqueness_of :content_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  has_many :contents, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_content, through: :likes, source: :content

  def already_liked?(content)
    self.likes.exists?(content_id: content.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def index
      if params[:tag]
        @contents = Content.order(created_at: :DESC).tagged_with(params[:tag]).includes(:taggings, :tags)
      else
        @contents = Content.all.order(created_at: :DESC).includes(:taggings, :tags)
      end
      @tags = ActsAsTaggableOn::Tag.most_used(20)
  end

  def new
    @post = Content.new
  end

  def create
    @post = Content.new(post_params)
    @post.save
    @post.tag_list.add(post_params[:tag_list],parse: true)
    @post.save
    redirect_to root_path
  end

  def show
    @content = Content.find(params[:id])
    @like = Like.new
    
  end

  def destroy
    @content = Content.find(params[:id])
    @content.tag_list.remove(@content.tag_list)
    @content.destroy
    @content.save
    redirect_to root_path
  end

  def edit
    @post = Content.find(params[:id])
  end

  def update
    @post = Content.find(params[:id])
    @content_update = @post.update(post_params)
    @post.tag_list = post_params[:tag_list]
    @post.save
    @post.reload
    @post.tags
    redirect_to root_path
  end

  def search_title
    @contents = Content.search_title(params[:keyword])
    @tags = ActsAsTaggableOn::Tag.most_used(20)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def search_content
    @contents = Content.search_content(params[:keyword])
    @tags = ActsAsTaggableOn::Tag.most_used(20)
    respond_to do |format|
      format.html
      format.json
    end
  end

  private

  def post_params
    params.require(:content).permit(:title, :content, :tag_list).merge(user_id: current_user.id)
  end


end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.new(content_id: params[:content_id])
    @like.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(content_id: params[:content_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contents/_index.html.haml
= render 'shared/top-title'

.wrapper
  .main
    .content-header
      %table
        %tr
          %th.content-header__tag.title-bar タグ
          %th.content-header__title.title-bar タイトル 
          %th.content-header__content.title-bar 説明
          %th.content-header__name.title-bar 投稿者

    .content-buttom  
      .content-box
        - @contents.each do |content|
          = link_to content_path(content.id) do
            %ul.line
              %li.content-box__tag
                = content.tag_list
              %li.content-box__title
                = content.title
              %li.content-box__content
                = content.content
              %li.content-box__name
                = content.user.name

  .side
    = render 'shared/top-side'

app/views/contents/edit.html.haml
= render 'shared/top-title'

= form_with model:@post, local: true, class: 'form' do |f|
  = f.text_field :title, placeholder: "タイトルを入力",class: 'form__title'
  = f.text_field :tag_list, value: @post.tag_list.join(','), class: 'form__tag',placeholder: "タグをカンマ区切りで入力"
  = f.text_area :content, placeholder: "内容を入力", class: 'form__content'
  = f.submit '再投稿', class: 'form__submit'

app/views/contents/index.html.haml
= render 'shared/top-index'

app/views/contents/new.html.haml
= render 'shared/top-title'

= form_with model:@post, local: true, class: 'form' do |f|
  = f.text_field :title, placeholder: "タイトルを入力",class: 'form__title'
  = f.text_field :tag_list, value: @post.tag_list.join(','), class: 'form__tag',placeholder: "タグをカンマ区切りで入力"
  = f.text_area :content, placeholder: "内容を入力", class: 'form__content'
  = f.submit '投稿', class: 'form__submit'

app/views/contents/search_content.html.haml
= render 'index'

app/views/contents/search_title.html.haml
= render 'shared/top-index'

app/views/contents/show.html.haml
= render 'shared/top-title'

.content_show
  .title
    .title__bar
      %h1
        タイトル
    
    .title__content
      .title__content__title
        = simple_format(@content.title)
      .title__content__items
        %ul
          %li
            - if user_signed_in? && current_user.id == @content.user.id
              = link_to '削除', content_path, method: :delete
              = link_to '編集', edit_content_path(@content.id)

    .title__bar-under
      .title__bar-under__like-box
        .title__bar-under__like-box__count
          いいね件数:
          = @content.likes.count
        .title__bar-under__like-box__action
          - if user_signed_in? && current_user.id == @content.user.id
            - if current_user.already_liked?(@content)
              = button_to 'いいねを取り消す', content_like_path(@content), method: :delete
            - else
              = button_to 'いいね', content_likes_path(@content)
      .title__bar-under__user-name 
        投稿者：
        = @content.user.name
      .title__bar-under__created_at 
        投稿日：
        = I18n.l @content.created_at, format: :long

    .title__tags
      タグ：
      .title__tags__tag
        - @content.tag_list.each do |tag|
          %ul
            %li
              = tag
      -# .title__updated_at
      -#   最終更新日:
      -#   = I18n.l @content.updated_at, format: :long




  .content
    .@content-box__content
      = safe_join(@content.content.split("\n"),tag(:br))

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ItDictionary
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'

  %body
    = yield

app/views/shared/_top-index.html.haml
= render 'shared/top-title'

.wrapper
  .main
    .content-header
      %table
        %tr
          %th.content-header__tag.title-bar タグ
          %th.content-header__title.title-bar タイトル 
          %th.content-header__content.title-bar 説明
          %th.content-header__name.title-bar 投稿者

    .content-buttom  
      .content-box
        - @contents.each do |content|
          = link_to content_path(content.id) do
            %ul.line
              %li.content-box__tag
                = content.tag_list
              %li.content-box__title
                = content.title
              %li.content-box__content
                = content.content
              %li.content-box__name
                = content.user.name

  .side
    = render 'shared/top-side'

app/views/shared/_top-side.html.haml
%p タイトル検索
.search-title
  = form_with url: search_title_contents_path, method: :get, local: true ,class: 'search-title__form-with' do |f|
    = f.text_field :keyword, placeholder: "検索したい文言を入力",class: "search-title__form-with__input"
    = f.submit "検索", class: "search-title__form-with__btn"

%p 説明検索
.search-content
  = form_with url: search_content_contents_path, method: :get, local: true ,class: 'search-content__form-with' do |f|
    = f.text_field :keyword, placeholder: "検索したい文言を入力",class: "search-content__form-with__input"
    = f.submit "検索", class: "search-content__form-with__btn"

%p 上位10位タグ
.tag-ranking
  %table
    %tr
      %th 順位
      %th タグ
      %th カウント

    - @tags.each_with_index do |tag,i|
      %tr
        %td
          = i + 1
        %td
          = tag.name
        %td
          = tag.taggings_count

app/views/shared/_top-title.html.haml
.top
  .title
    = link_to 'IT-Dictionary', root_path 

  .login
    - if user_signed_in?
      %ul
        %li
          = current_user.name
        %li
          = link_to '新規投稿', new_content_path, class: 'post'
        %li
          = link_to 'ログアウト',destroy_user_session_path,method: :delete ,class: 'logout'
    - else
      %ul
        %li
          = link_to 'ログイン', new_user_session_path, class: 'login'
        %li
          = link_to 'ユーザ登録', new_user_registration_path, class: 'user-register'

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", '#', class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'